<?php
$aMenuLinks = [
    [
        "telegram",
        "https://t.me/eatcactus",
        [],
        [],
        "",
    ],
    [
        "telegram",
        "https://t.me/bitrixdrifters",
        [],
        [],
        "",
    ],
    [
        "telegram",
        "https://t.me/not_givinig_up_developer",
        [],
        [],
        "",
    ],
    [
        "github",
        "https://github.com/bitrixdrifters",
        [],
        [],
        "",
    ],
    [
        "github",
        "https://github.com/olegnizamov",
        [],
        [],
        "",
    ],
    [
        "bitrix",
        "https://dev.1c-bitrix.ru/learning/resume.php?ID=64141782-752573",
        [],
        [],
        "",
    ],
    [
        "linkedin",
        "https://www.linkedin.com/in/olegnizamov/",
        [],
        [],
        "",
    ],
];
